### ISSUE TITLE
CIS load balancer pool's origin no longer allow private IPs

### ISSUE THREAD

**Issue by McBrosa** [ibm-cloud-docs/cis#34]
**Summary:**
Creating a CIS load balancer pool using a private IP or a record that resolves to a private IP is no longer supported by Cloudflare.

**Additional Info:**
https://support.cloudflare.com/hc/en-us/requests/1739883?page=1

**Comment by austinmama** [comment]
@sheltons

**Comment by sheltons** [comment]
Updated in staging. Closing this without merging to prod, to maintain docs procedures.
