### ISSUE TITLE
TLS Options visualization

### ISSUE THREAD

**Issue by phssakaigawa** [ibm-cloud-docs/cis#35]
Is it a good idea to describe the option using a graphic, as in the “Cloudflare SSL Configuration” section of CloudFlare?
If I pull-request, can you consider this?

https://www.cloudflare.com/ssl/

**Comment by austinmama** [comment]
@sheltons

**Comment by sheltons** [comment]
Made changes in staging. Will verify that the new images are ok, then merge. Closing this issue.
