### ISSUE TITLE
Clarifications on cis-cis-plan-comparison

### ISSUE THREAD

**Issue by mysteq** [ibm-cloud-docs/cis#36]
Can I make a few suggestions and questions regarding the Plan Comparison page ("https://cloud.ibm.com/docs/infrastructure/cis?topic=cis-cis-plan-comparison").

In table 1 it lists the following plan names and order, "Standard", "Enterprise Package or Usage", "Enterprise GLB", and "Enterprise Security".
In table 2 it lists the following plan names and order, "CIS Enterprise(Usage & Package plans available)", "CIS GLB", "CIS Security", and "CIS Standard(30 day no-cost trial available)".

I assume these are supposed to be the same plans, so can I suggest to use both the same names and ordering of the plans on the two tables?

In table 1 it lists the function "Range" with the values for "Enterprise Package or Usage" and "Enterprise Security" the following; "Yes, Total of 10 TB, 5 TB HTTPS, 5 TB Range" and "Same as Enterprise".
In table 2 it lists the function "CIS Range", which I assume is the same as the previous mentioned "Range", with the following values for the same plans as in table 1; "1 TB" and "0.1 TB".

Are the functions "Range" and "CIS Range" different functions, or do the values represent different mening in the two tables?

In table 1 and the function "DDoS" the value for "Enterprise Package or Usage" is "On (with Proxy) or Off (no Proxy)" and the value for "Enterprise Security" is "Yes". Do "Yes" mean that "DDoS" works differently on these two plans, and the Proxy is not possible to turn on or off on the DNS in the "Enterprise Security" plan, and it's an always on functionality?

Another thing, on the page "Getting started with IBM Cloud Internet Services" ("https://cloud.ibm.com/docs/infrastructure/cis?topic=cis-getting-started"), the following plans are listed:
```
There are 4 plans to choose from,

Enterprise Usage
Enterprise Package
Standard Plan
Free Trial.
```

This does not list "Enterprise Security" nor "Enterprise GLB" as available plans, altho the other page suggests they are.

**Comment by austinmama** [comment]
@sheltons

**Comment by sheltons** [comment]
The plan list in Getting Started is updated, and I will work with the OM to help make the table clearer in the Comparison page.

**Comment by sheltons** [comment]
Closing this issue, because we're tracking it in the staging repo now.
