### ISSUE TITLE
Metadata from markdown showing in render

### ISSUE THREAD

**Issue by cloudpitchford** [ibm-cloud-docs/cis#42]
https://cloud.ibm.com/docs/cis?topic=cis-use-page-rules has some text that is supposed to be part of the metadata.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/49790046/97031379-6b197f00-151d-11eb-8bfa-86809c02bf18.png">

**Comment by sheltons** [comment]
Fixed. Thank you for notifying us!
