### ISSUE TITLE
CIS - Managing access steps

### ISSUE THREAD

**Issue by sumanthr1** [ibm-cloud-docs/cis#45]
This page should say the name of the service to request access for to be able to use CIS. I believe it is 'Internet Services' in the Assign Policies/IAM section of Access Groups in the IBM Cloud Console. 

A step by step guide like in this page, https://cloud.ibm.com/docs/dns/getting-started.html , would help here as well.

**Comment by austinmama** [comment]
@sheltons

**Comment by sumanthr1** [comment]
It will be helpful to see a reference (URL or pull request) to the final update here. That way anyone visiting this issue with a similar problem can see the solution. Thanks!
