### ISSUE TITLE
In the CIS interface there is an error

### ISSUE THREAD

**Issue by psacchit** [ibm-cloud-docs/cis#46]
In the CIS interface for Security -> Origin -> View Certificate. It says
"To install a certificate on your origin server, copy the following key and certificate, then paste them into the files on your web server.
View documentation for installing certificates on various web servers."
Only all I see is the Certificate. No key.
![image](https://user-images.githubusercontent.com/56307344/122453006-e1b93000-cf77-11eb-8253-b39232ab8978.png)

**Comment by sheltons** [comment]
The private key is only displayed one time, right after you order the certificate. 
![image](https://user-images.githubusercontent.com/20952798/122819121-a1bbbb00-d29f-11eb-8d41-87deafb67bf8.png)

If you are viewing this page after the initial order, the key is no longer displayed.

**Comment by sheltons** [comment]
Adding "important" tag to the information in docs, and passed info to the dev team to make the UI more clear that it's a one-time opportunity to capture the key information at ordering.
