### ISSUE TITLE
Defense mode widget has changed in UI

### ISSUE THREAD

**Issue by mriedem** [ibm-cloud-docs/cis#49]
The docs here https://cloud.ibm.com/docs/cis?topic=cis-faq#cis-faq-what-to-do-in-ddos show this:

![image](https://user-images.githubusercontent.com/3237936/174336993-c81ca451-4f80-4db6-ad82-ddeafc58d4c8.png)

But in the Overview UI I see today there are toggles rather than a dropdown:

![image](https://user-images.githubusercontent.com/3237936/174337055-2de2c523-04db-4fdf-8670-09672431376e.png)

**Comment by sheltons** [comment]
Image updated. Thanks for the note.
