### ISSUE TITLE
Logpush and Logpull missing in the plan comparison

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/cis#56]
Logpush and Logpull missing in the Table 1 CIS plan comparison of this page
https://cloud.ibm.com/docs/cis?topic=cis-cis-plan-comparison

Recommendation:
Add one row for Logpush/Logpull in this table.

**Comment by lionelmace** [comment]
Logpush and Logpull is also missing from the `Table 2. Comparison of CIS Enterprise Tier plans`
https://cloud.ibm.com/docs/cis?topic=cis-transition-plans

**Comment by sheltons** [comment]
I've updated the documentation to reflect logging. Thanks for the catch!

**Comment by lionelmace** [comment]
Thank you. Can you please add Logging in this table

<img width="975" alt="image" src="https://github.com/ibm-cloud-docs/cis/assets/12241613/b726fb26-d3d6-43f6-ad36-79842224acc9">
