### ISSUE TITLE
Opening paragraph does not make sense

### ISSUE THREAD

**Issue by dlentzIBM** [ibm-cloud-docs/cis#58]
Hi, please see this document live and notice the following text is the entire opening paragraph:

`Read some specific instructions about how to configure your IBM Cloud® Internet Services Domain Name System (DNS) records, including how to configure Secure DNS.`

The title of the document is "Setting up you Domain Name System" for CIS, I was kind of expecting to see some explanatory high level statements that tell the reader why they have to update their DNS records.

Could you please have a look? thanks!

**Comment by sheltons** [comment]
@dlentzIBM Thanks for reaching out. Because I can't make changes directly to production, I'll be moving these issues to our staging repository where editing is possible. I'll follow up with you there.
