### ISSUE TITLE
Several changes to enhance readability

### ISSUE THREAD

**Issue by dlentzIBM** [ibm-cloud-docs/cis#59]
Hi, please consider making the following changes:

## Before you begin section
In the 'Before You Begin' section we need to inform the reader of the supported options for domains in CIS. This is where a reader can make a decision as to if CIS will work for them or not based on how the reader has to manage their domain. Something along the lines of: `User your existing Domain by adding

I'd highly recommend:
1. In the navigation links (on left side) of this document, rename `Using best practices' to 'Best Practices'.  A section called 'Using best practices' is confusing
1. Rename the [Best practices for CIS Setup](https://cloud.ibm.com/docs/cis?topic=cis-best-practices-for-cis-setup) page to `CIS Setup`. It is redundant to have the name of the section also in the name of the child oage.
1. Create a new  page called 'Working with Domains' in the 'Best Practice' category.  This page should explain in detail why IBM (or Cloudflare) recommends importing DNS records into CIS. In addition this new page should be the **only document that lists the steps to import the DNS record when adding a domain. Elsewhere in the CIS Cloud Docs we state that we recommend to do this, would be good to explain why

## Keep the Process Overview, provide links to the details 
We shouldn't have granular steps to perform a function of an IBM Cloud service on the 'Getting Started' page. Instructional steps to perform a task on/with the service should have dedicated page in the CIS Cloud Docs.

Each numbered item in the Process Overview should be a link to a page that details how to perform that part of the process.

## Step 1 - Open the IBM CIS application <- makes no sense
Step 1 in the Process Overview should read "Provision a new instance of IBM Cloud Internet Services". This step in the overview should give the users a one-click link to provision CIS. In other words, Step 1 in the process overview should be:
```
1. Provision an instance of the [IBM Cloud Internet Services](https://cloud.ibm.com/catalog/services/internet-services)
```
Obviously you'd use the variable name for the service but you get the idea.

Remove the entire 'Select a plan' section of this document. The plans are not aligned with what is available on the provisioning page and this doc gives no details about what each license does (the provisioning page does). Replace the 'Select a Plan' section with this text which points the reader to the provisioning page to read about the licenses.

```
For details on each plan IBM Cloud Internet Services provides, please see the [CIS Provisioning Page](https://cloud.ibm.com/catalog/services/internet-services)
```

This document shows deprecation dates of licenses. Instead of listing that on the Getting STarted page, it should be listed on a CIS Change Log page. The SCC Team has a great example of a Change Log, [check it out](https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-fs-change-log)

## Don't use the word 'Screen' when you should be using 'Page'
Reading section titles like 'The Overview screen' should really be reworded to 'The Overview page'.   I'd grep (or search) through these cloud docs and really question if the use of the word 'screen' should be changed to 'Page'.

**Comment by sheltons** [comment]
Moving issue to staging repo where it can be acted upon. I'll follow up with you there.
