### ISSUE TITLE
A couple of minor changes to increase readability

### ISSUE THREAD

**Issue by dlentzIBM** [ibm-cloud-docs/cis#60]
Hi,
Would you please consider making these updates:

1. The second paragraph begins with `To add an additional domain to your CIS instance` , please change this to `To add a domain to your CIS instance`. The word additional is redundant after using the word add. Also, first time CIS users would not have added a domain yet, so referring to adding 'additional' domains is kind of confusing unless there is a different process between adding the first domain and adding additional domains.

2. The user may not know what the 'Overview' page is. Instead of telling the user to go to the Overview page you should tell them to navigate to their CIS instance (which sadly is much more difficult than it should be). 

Well ......... I was going to list  other changes needed but I figured I'd just write the changes I'm proposing and give them to you here (I doubt I can create a PR). 

Why should these changes be made? This page is linked to from countless tutorials and other cloud docs. It should be assumed that when the reader arrives on the page that the user:
- May not be the same user who provisioned the CIS instance. The user who provisions and the user who configures a service very well may have mutually exclusive access granted to support Separation of Duty.
- May have closed or lost their browser tab they had open when they provisioned CIS and they must now figure out how to get back to the CIS instance would have the user who 'Provisions' a service have provisioned CIS but they might have closed their browser tab after provisioning, or more likely one user provisioned the service and nother team member needs to add a domain

## Here's the code addressing everything above
Have I seen the rendered output of the code below? Nope, just wrote that stuff from memory. If there are errors in the code they should be minimal/easy to fix

Hit me on slack (dlentz@us.ibm.com) if you would prefer to have a conversation about this change.

```

## Navigate to your {{site.data.keyword.cis_short_notm}} instance
{: #navigate-to-cis-instance}
{: step}

1. Locate the instance of {{site.data.keyword.cis_short_notm}} in your IBM Cloud Resources by clicking  [here](https://cloud.ibm.com/resources?product=Internet+Services){: external}
1. Click on the name of the {{site.data.keyword.cis_short_notm}} instance.

## Adding a domain to {{site.data.keyword.cis_short_notm}} instance
{: #add-domain-to-cis-instance}
{: step}

1. If there are no domains in the  {{site.data.keyword.cis_short_notm}} instance press the blue 'Add Domain' button and skip to **Step 3**.
1. If there are domains listed at the top of the  {{site.data.keyword.cis_short_notm}} instance page click the "..." overflow menu on the same row as the Domain and select **New Domain**.
1. A section will appear on the right side of the page which will step you through Connecting the domain, 
1. Enter the name of the Domain and click Next
1. It is recommended that you import or recreate your DNS records in {{site.data.keyword.cis_short_notm}} . Import the DNS records you've exported from your current DNS, or manually create your DNS records. To import records, select Import records.
1. Delegate your Domain to {{site.data.keyword.cis_short_notm}}  in order to receive all benefits of your chosen plan. [Learn more about delegating domain management](https://cloud.ibm.com/docs/cis?topic=cis-getting-started#configure-your-name-servers-with-the-registrar-or-existing-dns-provider)

The {{site.data.keyword.cis_short_notm}} instance will detect when the domain delegation is complete automatically. Domain delegation can take several hours to a day depending on the DNS service being used to delegate.

At this point the Domain is added to {{site.data.keyword.cis_short_notm}} however it will remain in `Pending` status until {{site.data.keyword.cis_short_notm}} detects the domain delegation is complete.

If you lose connection to the IBM Cloud console, or close your web browser you can check the status of the Domain by navigating to the {{site.data.keyword.cis_short_notm}} instance page on the IBM Cloud console.
```

## This is really the last thing
I submitted a new issue against the [CIS Getting Started page](https://cloud.ibm.com/docs/cis?topic=cis-getting-started). [Issue 59](https://github.com/ibm-cloud-docs/cis/issues/59) coincides with the issues on this page.

**Comment by sheltons** [comment]
Moving issue to staging repo where it can be acted upon. I'll follow up with you there.
