### ISSUE TITLE
Advanced rate limiting feature is not currently available.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/cis#61]
Hello,

The following page says that `advanced rate limiting` is available for Enterprise Advanced/Premier plan, but it is not actually available. Please correct this.
https://cloud.ibm.com/docs/cis?topic=cis-transition-plans#transitioning-enterprise-plans

Please check this thread for the details.
https://ibm-cloudplatform.slack.com/archives/C8XKQ9FPB/p1708032939592609?thread_ts=1707887704.121239&cid=C8XKQ9FPB

Best regards,

**Comment by sheltons** [comment]
I've pushed the corrected page to production. Closing.
